# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientCategory',
        ),
    ]
