# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0004_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='slug',
            field=models.SlugField(default='alcohol', max_length=200),
            preserve_default=False,
        ),
    ]
