# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0007_auto_20160709_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Recipe')),
            ],
            options={
                'ordering': ['recipe', 'order'],
            },
        ),
    ]
