# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0018_auto_20160709_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstep',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredientstep',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Unit'),
        ),
    ]
