# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0021_auto_20160710_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
