# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0032_source_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstep',
            name='amount_den',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingredientstep',
            name='amount_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
