# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0036_recipe_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='step',
            name='amount_den_foo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='step',
            name='amount_num_foo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='ingredient_foo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='unit_foo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Unit'),
        ),
    ]
