# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0037_auto_20160806_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientstep',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='ingredientstep',
            name='unit',
        ),
        migrations.DeleteModel(
            name='IngredientStep',
        ),
    ]
