# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0039_auto_20160806_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount_den_foo',
            new_name='amount_den',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount_num_foo',
            new_name='amount_num',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_foo',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='unit_foo',
            new_name='unit',
        ),
    ]
