# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0040_auto_20160806_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='cocktails_app.RecipeIngredient', to='cocktails_app.Ingredient'),
        ),
    ]
