# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0041_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
