# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0044_auto_20160924_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_public',
        ),
    ]
