# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0046_recipe_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='should_show_glass_label',
            field=models.BooleanField(default=True),
        ),
    ]
