# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0047_glass_should_show_glass_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
