# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0054_auto_20210402_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.RecipeCategory'),
        ),
    ]
