# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 01:53
from __future__ import unicode_literals

from django.db import migrations


def add_categories_from_category(apps, schema_editor):
    Recipe = apps.get_model('cocktails_app', 'Recipe')

    for recipe in Recipe.objects.all():
        recipe.categories.add(recipe.category)
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0056_auto_20210524_0150'),
    ]

    operations = [
        migrations.RunPython(add_categories_from_category)
    ]
