# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0058_auto_20210524_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cocktails_app.RecipeCategory'),
        ),
    ]
