# Generated by Django 3.2.14 on 2022-08-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0060_auto_20210525_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glass',
            options={'ordering': ['name'], 'verbose_name_plural': 'Glasses'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ingredient categories'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Recipe categories'},
        ),
    ]
