# Generated by Django 3.2.18 on 2023-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0061_auto_20220805_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='encrypted_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
