# Generated by Django 3.2.18 on 2023-04-04 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0062_recipe_encrypted_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='encrypted_slug',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
