# Generated by Django 4.1.9 on 2023-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0063_alter_recipe_encrypted_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='cocktails_app.recipetag'),
        ),
    ]
