# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0003_ingredientcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default='Alcohol', on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.IngredientCategory')),
            ],
        ),
    ]
