# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0005_ingredientcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
