# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0009_actionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='actionstep',
            name='name',
        ),
        migrations.AddField(
            model_name='actionstep',
            name='action',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Action'),
        ),
    ]
