# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0016_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='unit',
            name='plural',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
