# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0025_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.Source'),
        ),
    ]
