# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0031_auto_20160717_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
